teacher:
  prob: 1.0
  BATCH: 0.4
  input_perturb: 0.0
  batch_size: 3072
  model_path: model/32x32_diffusion_cifar10.pt
  iter_choice: dynamic_iterative_distillation
  tempfile: experiments/cache/CIFAR10-Dynamic-0.4.cache

  model: yaml/arch/57M-CNN.yaml
  diffusion: yaml/cifar10_32/diffusion.yaml

student:
  schedule_sampler: uniform
  lr: 0.0001
  weight_decay: 0.0
  lr_anneal_steps: 0
  batch_size: 128
  microbatch: -1
  ema_rate: "0.9999"
  resume_checkpoint: ''
  use_fp16: true
  fp16_scale_growth: 0.001

  model_path: ''
  log_interval: 10
  save_interval: 10000
  cache_save_interval: -1

  model: yaml/arch/32M-CNN.yaml
  diffusion: yaml/cifar10_32/diffusion.yaml